### ISSUE TITLE
[Swipe to refresh] Accompanist implementation is now deprecated, but the new official implementation is bugged

### ISSUE THREAD

**Issue by leinardi** [google/accompanist#1417]
**Description**
I just want to point out that the new [official pull refresh](https://developer.android.com/reference/kotlin/androidx/compose/material/pullrefresh/package-summary) of has issues so you should probably reconsider the deprecation of the Accompanist implementation, until this issue is solved: 
https://issuetracker.google.com/issues/260272363

We migrated our code base since the Accompanist implementation got deprecated, but this new implementation doesn't work well if the loading times are very short (e.g. the content is already cached).

We have already reported the issue on the official Google tracker. We are not aware of any workaround for this issue, beside artificially increase the loading time of the data controlling the refresh status.

**Comment by bentrengrove** [comment]
Looks like that issue has been fixed in the next release. We won't be removing SwipeRefresh from accompanist for at least another release of Compose so you can still use it if you need.

The deprecation will stay though because there will be no more bug fixes here.

**Comment by gajicm93** [comment]
> Looks like that issue has been fixed in the next release. We won't be removing SwipeRefresh from accompanist for at least another release of Compose so you can still use it if you need.
> 
> The deprecation will stay though because there will be no more bug fixes here.

Regarding removal, keep in mind that component has been implemented into Material2 library, but NOT Material3, so as someone who has a project build on Material3, there is still not an option for me to migrate and I have to stay relying on Accompanist implementation.. Also there is no info from Google on when this will be implemented in Material3.. I'm actually pretty enraged over this by now.. @bentrengrove

**Comment by bentrengrove** [comment]
I promise we won't remove it from here until all use cases are working. The Accompanist version is also a material 2 implementation but you can continue to use it if it suits your needs
