### ISSUE TITLE
[WebView] Modifier pullRefresh not work for WebView

### ISSUE THREAD

**Issue by ssujr** [google/accompanist#1670]
Trying to add Modifier.pullRefresh() to WebView as below which is not working.

`    val navigator = rememberWebViewNavigator()`
`    val state = rememberWebViewState(url = "https://www.google.com")`
`    val scope = rememberCoroutineScope()`
`    fun refresh() = scope.launch {`
`        navigator.reload()`
`    }`
`    val refreshState = rememberPullRefreshState(isLoading, ::refresh)`
` `
`    WebView(`
`                modifier = Modifier.fillMaxSize().pullRefresh(refreshState),`
`                state = state,`
`                navigator = navigator`
`    )`

**Comment by bentrengrove** [comment]
Please try this again in the latest release, this should have been fixed by #1684

**Comment by ssujr** [comment]
Tried v0.31.6-rc. androidx.compose.material.pullrefresh is still not working.

**Comment by bentrengrove** [comment]
Unfortunately Accompanist WebView has been deprecated and won't be supported going forwards. I am closing this issue. We recommend you fork the implemenation here and customise it to your needs. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)
