### ISSUE TITLE
nested pager gesture bug

### ISSUE THREAD

**Issue by crayonxiaoxin** [google/accompanist#325]
## Describe the bug
When a pager is nested in another pager, the outer set `dragEnabled = false`, when the inner one is dragged, it can still scroll.
source code: [https://github.com/crayonxiaoxin/WanAndroid.git](url)

## Screenshots?
![ezgif-4-223e1d2ee06c](https://user-images.githubusercontent.com/35017508/114405082-e4468480-9bd8-11eb-9e9d-275e5624fa1e.gif)

## Environment:
 - Android OS version: Android 11
 - Device: Mi 10 Ultra
 - Accompanist version: 0.7.1

**Comment by chrisbanes** [comment]
There's actually 2 issues here:

- `PagerState` wasn't property consuming drag events. Fixed in 8fb3644c9c54863d036fc556fb5756dd16de5c67
- `Modifier.scrollable(enabled = false)` still allows nested scrolls: https://issuetracker.google.com/issues/185057631

**Comment by crayonxiaoxin** [comment]
@chrisbanes In v0.8.0，the issues still exists. When swiping quickly in the opposite direction，the root Pager still be scrolled by nested HorizontalPager.

**Comment by chrisbanes** [comment]
Thanks for the update, but you don't need to ping the issue 👍 . It's still open, and we're waiting on the Compose bug linked above.

**Comment by chrisbanes** [comment]
The Compose bug has been fixed and it will be in the next Jetpack Compose release. I've verified that it works as expected, so closing this.
